<?php
$data = array (
  0 => 
  array (
    'cat_id' => '19',
    'cat_name' => '新手指南',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '10',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '5',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '系统分类',
    'cat_type' => '2',
    'keywords' => '',
    'cat_desc' => '系统保留分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '2',
    'aricle_num' => '0',
  ),
  2 => 
  array (
    'cat_id' => '14',
    'cat_name' => '如何付款',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '5',
  ),
  3 => 
  array (
    'cat_id' => '15',
    'cat_name' => '配送方式',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '5',
  ),
  4 => 
  array (
    'cat_id' => '20',
    'cat_name' => '服务中心',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '60',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '5',
  ),
  5 => 
  array (
    'cat_id' => '21',
    'cat_name' => '热门活动',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '70',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  6 => 
  array (
    'cat_id' => '22',
    'cat_name' => '最新动态',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '80',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  7 => 
  array (
    'cat_id' => '2',
    'cat_name' => '网店信息',
    'cat_type' => '3',
    'keywords' => '',
    'cat_desc' => '网店信息分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  8 => 
  array (
    'cat_id' => '3',
    'cat_name' => '网店帮助分类',
    'cat_type' => '4',
    'keywords' => '',
    'cat_desc' => '网店帮助分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '6',
    'aricle_num' => '0',
  ),
  9 => 
  array (
    'cat_id' => '6',
    'cat_name' => '手机常识 ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '手机常识 ',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  10 => 
  array (
    'cat_id' => '7',
    'cat_name' => '配送与支付 ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '配送与支付 ',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  11 => 
  array (
    'cat_id' => '8',
    'cat_name' => '服务保证 ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  12 => 
  array (
    'cat_id' => '9',
    'cat_name' => '联系我们 ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '联系我们 ',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  13 => 
  array (
    'cat_id' => '10',
    'cat_name' => '会员中心',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  14 => 
  array (
    'cat_id' => '5',
    'cat_name' => '新手上路 ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
);
?>