<?php
$data = array (
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '蛋糕预定',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '蛋糕预定',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '按材料',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '10',
    'goods_num' => 0,
    'level' => 1,
    'id' => '6',
    'name' => '按材料',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '鲜奶蛋糕',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 16,
    'level' => 2,
    'id' => '11',
    'name' => '鲜奶蛋糕',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '彩虹蛋糕',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => 12,
    'level' => 2,
    'id' => '12',
    'name' => '彩虹蛋糕',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '水果蛋糕',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '0',
    'goods_num' => 46,
    'level' => 2,
    'id' => '14',
    'name' => '水果蛋糕',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '慕斯蛋糕',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '15',
    'level' => 2,
    'id' => '15',
    'name' => '慕斯蛋糕',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => '冰激凌蛋糕',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '110',
    'name' => '冰激凌蛋糕',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '芝士蛋糕',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '16',
    'name' => '芝士蛋糕',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '无糖蛋糕',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '70',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '17',
    'name' => '无糖蛋糕',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '翻糖蛋糕',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '80',
    'has_children' => '0',
    'goods_num' => 15,
    'level' => 2,
    'id' => '18',
    'name' => '翻糖蛋糕',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '黑森林蛋糕',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '90',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '19',
    'name' => '黑森林蛋糕',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '巧克力蛋糕',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '100',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '20',
    'name' => '巧克力蛋糕',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '按用途',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '7',
    'name' => '按用途',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '生日蛋糕',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 45,
    'level' => 2,
    'id' => '21',
    'name' => '生日蛋糕',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '祝寿蛋糕',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => 24,
    'level' => 2,
    'id' => '22',
    'name' => '祝寿蛋糕',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '情侣蛋糕',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '0',
    'goods_num' => 29,
    'level' => 2,
    'id' => '23',
    'name' => '情侣蛋糕',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '节日蛋糕',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '24',
    'name' => '节日蛋糕',
  ),
  111 => 
  array (
    'cat_id' => '111',
    'cat_name' => '庆典蛋糕',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '111',
    'name' => '庆典蛋糕',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '婚庆蛋糕',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '25',
    'name' => '婚庆蛋糕',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '儿童蛋糕',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '0',
    'goods_num' => 28,
    'level' => 2,
    'id' => '26',
    'name' => '儿童蛋糕',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '圣诞蛋糕',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '70',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '27',
    'name' => '圣诞蛋糕',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '按造型',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '8',
    'name' => '按造型',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '心形蛋糕',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '28',
    'name' => '心形蛋糕',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '方形蛋糕',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '29',
    'name' => '方形蛋糕',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '圆形蛋糕',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '30',
    'name' => '圆形蛋糕',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '多层蛋糕',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '0',
    'goods_num' => 29,
    'level' => 2,
    'id' => '31',
    'name' => '多层蛋糕',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '艺术蛋糕',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '32',
    'name' => '艺术蛋糕',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '生肖蛋糕',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '33',
    'name' => '生肖蛋糕',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '按对象',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '9',
    'name' => '按对象',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '恋人蛋糕',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '34',
    'name' => '恋人蛋糕',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => '长辈蛋糕',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '35',
    'name' => '长辈蛋糕',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => '朋友蛋糕',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '36',
    'name' => '朋友蛋糕',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => 'baby蛋糕',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '37',
    'name' => 'baby蛋糕',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => '按价格',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '10',
    'name' => '按价格',
  ),
  39 => 
  array (
    'cat_id' => '39',
    'cat_name' => '200-300元',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '39',
    'name' => '200-300元',
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => '300-1000元',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '40',
    'name' => '300-1000元',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => '1000元以上',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '41',
    'name' => '1000元以上',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => '100-200元',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '38',
    'name' => '100-200元',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '鲜花速递',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '2',
    'name' => '鲜花速递',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => '花材选购',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '42',
    'name' => '花材选购',
  ),
  76 => 
  array (
    'cat_id' => '76',
    'cat_name' => '-康乃馨-',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '76',
    'name' => '-康乃馨-',
  ),
  73 => 
  array (
    'cat_id' => '73',
    'cat_name' => '-白玫瑰-',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '73',
    'name' => '-白玫瑰-',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => '-郁金香-',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '77',
    'name' => '-郁金香-',
  ),
  74 => 
  array (
    'cat_id' => '74',
    'cat_name' => '-蓝玫瑰-',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '74',
    'name' => '-蓝玫瑰-',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => '-红玫瑰-',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '71',
    'name' => '-红玫瑰-',
  ),
  78 => 
  array (
    'cat_id' => '78',
    'cat_name' => '-香槟玫瑰-',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '78',
    'name' => '-香槟玫瑰-',
  ),
  75 => 
  array (
    'cat_id' => '75',
    'cat_name' => '-百合-',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '75',
    'name' => '-百合-',
  ),
  72 => 
  array (
    'cat_id' => '72',
    'cat_name' => '-粉玫瑰-',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '72',
    'name' => '-粉玫瑰-',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => '按用途',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '43',
    'name' => '按用途',
  ),
  70 => 
  array (
    'cat_id' => '70',
    'cat_name' => '-生日-',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '70',
    'name' => '-生日-',
  ),
  64 => 
  array (
    'cat_id' => '64',
    'cat_name' => '-爱情-',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '64',
    'name' => '-爱情-',
  ),
  68 => 
  array (
    'cat_id' => '68',
    'cat_name' => '-探望-',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '68',
    'name' => '-探望-',
  ),
  65 => 
  array (
    'cat_id' => '65',
    'cat_name' => '-祝福-',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '65',
    'name' => '-祝福-',
  ),
  66 => 
  array (
    'cat_id' => '66',
    'cat_name' => '-友情-',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '66',
    'name' => '-友情-',
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => '-道歉-',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '69',
    'name' => '-道歉-',
  ),
  67 => 
  array (
    'cat_id' => '67',
    'cat_name' => '-商务-',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '67',
    'name' => '-商务-',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => '按对象',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '44',
    'name' => '按对象',
  ),
  79 => 
  array (
    'cat_id' => '79',
    'cat_name' => '-恋人-',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '79',
    'name' => '-恋人-',
  ),
  86 => 
  array (
    'cat_id' => '86',
    'cat_name' => '-孩子-',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '86',
    'name' => '-孩子-',
  ),
  83 => 
  array (
    'cat_id' => '83',
    'cat_name' => '-同事-',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '83',
    'name' => '-同事-',
  ),
  80 => 
  array (
    'cat_id' => '80',
    'cat_name' => '-朋友-',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '80',
    'name' => '-朋友-',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => '-老师-',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '84',
    'name' => '-老师-',
  ),
  81 => 
  array (
    'cat_id' => '81',
    'cat_name' => '-父母-',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '81',
    'name' => '-父母-',
  ),
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => '-客户-',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '85',
    'name' => '-客户-',
  ),
  82 => 
  array (
    'cat_id' => '82',
    'cat_name' => '-病人-',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '82',
    'name' => '-病人-',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => '按节日',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '9',
    'goods_num' => 0,
    'level' => 1,
    'id' => '45',
    'name' => '按节日',
  ),
  108 => 
  array (
    'cat_id' => '108',
    'cat_name' => '-年春节-',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '108',
    'name' => '-年春节-',
  ),
  105 => 
  array (
    'cat_id' => '105',
    'cat_name' => '-教师节-',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '105',
    'name' => '-教师节-',
  ),
  102 => 
  array (
    'cat_id' => '102',
    'cat_name' => '-七夕节-',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '102',
    'name' => '-七夕节-',
  ),
  109 => 
  array (
    'cat_id' => '109',
    'cat_name' => '-妇女节-',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '109',
    'name' => '-妇女节-',
  ),
  106 => 
  array (
    'cat_id' => '106',
    'cat_name' => '-中秋节-',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '106',
    'name' => '-中秋节-',
  ),
  103 => 
  array (
    'cat_id' => '103',
    'cat_name' => '-母亲节-',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '103',
    'name' => '-母亲节-',
  ),
  107 => 
  array (
    'cat_id' => '107',
    'cat_name' => '-圣诞节-',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '107',
    'name' => '-圣诞节-',
  ),
  104 => 
  array (
    'cat_id' => '104',
    'cat_name' => '-父亲节-',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '104',
    'name' => '-父亲节-',
  ),
  101 => 
  array (
    'cat_id' => '101',
    'cat_name' => '-情人节-',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '101',
    'name' => '-情人节-',
  ),
  46 => 
  array (
    'cat_id' => '46',
    'cat_name' => '按枝数',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '46',
    'name' => '按枝数',
  ),
  95 => 
  array (
    'cat_id' => '95',
    'cat_name' => '-99支-',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '95',
    'name' => '-99支-',
  ),
  92 => 
  array (
    'cat_id' => '92',
    'cat_name' => '-21支-',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '92',
    'name' => '-21支-',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => '-33支-',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '93',
    'name' => '-33支-',
  ),
  89 => 
  array (
    'cat_id' => '89',
    'cat_name' => '-11支-',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '89',
    'name' => '-11支-',
  ),
  94 => 
  array (
    'cat_id' => '94',
    'cat_name' => '-66支-',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '94',
    'name' => '-66支-',
  ),
  90 => 
  array (
    'cat_id' => '90',
    'cat_name' => '-19支-',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '90',
    'name' => '-19支-',
  ),
  47 => 
  array (
    'cat_id' => '47',
    'cat_name' => '按价格',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '47',
    'name' => '按价格',
  ),
  98 => 
  array (
    'cat_id' => '98',
    'cat_name' => '-301-500元-',
    'measure_unit' => '',
    'parent_id' => '47',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '98',
    'name' => '-301-500元-',
  ),
  99 => 
  array (
    'cat_id' => '99',
    'cat_name' => '-501-800元-',
    'measure_unit' => '',
    'parent_id' => '47',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '99',
    'name' => '-501-800元-',
  ),
  96 => 
  array (
    'cat_id' => '96',
    'cat_name' => '-100-200元-',
    'measure_unit' => '',
    'parent_id' => '47',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '96',
    'name' => '-100-200元-',
  ),
  100 => 
  array (
    'cat_id' => '100',
    'cat_name' => '-800元以上-',
    'measure_unit' => '',
    'parent_id' => '47',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '100',
    'name' => '-800元以上-',
  ),
  97 => 
  array (
    'cat_id' => '97',
    'cat_name' => '-201-300元-',
    'measure_unit' => '',
    'parent_id' => '47',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '97',
    'name' => '-201-300元-',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '花材组合',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '3',
    'name' => '花材组合',
  ),
  48 => 
  array (
    'cat_id' => '48',
    'cat_name' => '玫瑰百合组合',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '48',
    'name' => '玫瑰百合组合',
  ),
  49 => 
  array (
    'cat_id' => '49',
    'cat_name' => '百合乃馨组合',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '49',
    'name' => '百合乃馨组合',
  ),
  50 => 
  array (
    'cat_id' => '50',
    'cat_name' => '多色玫瑰组合',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '50',
    'name' => '多色玫瑰组合',
  ),
  51 => 
  array (
    'cat_id' => '51',
    'cat_name' => '各种花材组合',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '51',
    'name' => '各种花材组合',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '浪漫组合',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '4',
    'name' => '浪漫组合',
  ),
  52 => 
  array (
    'cat_id' => '52',
    'cat_name' => '鲜花蛋糕',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '52',
    'name' => '鲜花蛋糕',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '特色礼品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '5',
    'name' => '特色礼品',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => '品牌巧克力',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '55',
    'name' => '品牌巧克力',
  ),
  53 => 
  array (
    'cat_id' => '53',
    'cat_name' => '毛绒玩具',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '53',
    'name' => '毛绒玩具',
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => '开业花篮',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '54',
    'name' => '开业花篮',
  ),
);
?>